# Generated by Django 2.1.5 on 2019-01-24 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('abs_page_linkabstract', models.TextField()),
                ('abstract', models.TextField()),
                ('all_categories', models.TextField()),
                ('arxiv_id', models.TextField()),
                ('author', models.TextField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('journal_ref', models.TextField()),
                ('last_author', models.TextField()),
                ('pdf_link', models.TextField()),
                ('primary_category', models.TextField()),
                ('published', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
